export const ANIME_LIBRARY = [
	{
		id: 1,
		title: "Silent Lantern",
		jp: "静かな灯",
		type: "TV" as const,
		ep: 24,
		aired: "Spring 2026",
		studio: "Studio Maple",
		genres: ["Drama", "Mystery"],
		score: 8.74,
		members: 412_850,
		status: "Airing" as const,
		glyph: "静",
		progress: 7,
		color: "#5b8bff",
	},
	{
		id: 2,
		title: "Crimson Signal",
		jp: "紅信号",
		type: "TV" as const,
		ep: 12,
		aired: "Winter 2026",
		studio: "BrightStone",
		genres: ["Sci-Fi", "Action"],
		score: 8.41,
		members: 298_220,
		status: "Completed" as const,
		glyph: "紅",
		progress: 12,
		color: "#f43f79",
	},
	{
		id: 3,
		title: "Paperbound",
		jp: "紙の境界",
		type: "TV" as const,
		ep: 13,
		aired: "Fall 2025",
		studio: "Origami Pictures",
		genres: ["Slice of Life", "Drama"],
		score: 8.95,
		members: 522_010,
		status: "Watching" as const,
		glyph: "紙",
		progress: 9,
		color: "#34d3b7",
	},
	{
		id: 4,
		title: "Hollow Orchestra",
		jp: "虚ろな楽団",
		type: "Film" as const,
		ep: 1,
		aired: "2025",
		studio: "Studio Maple",
		genres: ["Music", "Fantasy"],
		score: 9.12,
		members: 188_770,
		status: "Completed" as const,
		glyph: "虚",
		progress: 1,
		color: "#a78bfa",
	},
	{
		id: 5,
		title: "Bureau of Small Miracles",
		jp: "小さな奇跡局",
		type: "TV" as const,
		ep: 24,
		aired: "Spring 2026",
		studio: "Koinuma Films",
		genres: ["Supernatural", "Comedy"],
		score: 7.83,
		members: 94_110,
		status: "Watching" as const,
		glyph: "奇",
		progress: 3,
		color: "#f5b454",
	},
	{
		id: 6,
		title: "Dust & Iron",
		jp: "塵と鉄",
		type: "TV" as const,
		ep: 26,
		aired: "Fall 2025",
		studio: "Granite Arts",
		genres: ["Mecha", "War"],
		score: 8.27,
		members: 241_330,
		status: "On Hold" as const,
		glyph: "鉄",
		progress: 14,
		color: "#6f77a6",
	},
	{
		id: 7,
		title: "Sakura in the Wires",
		jp: "電線の桜",
		type: "TV" as const,
		ep: 12,
		aired: "Spring 2026",
		studio: "BrightStone",
		genres: ["Cyberpunk", "Romance"],
		score: 8.02,
		members: 137_440,
		status: "Plan to Watch" as const,
		glyph: "桜",
		progress: 0,
		color: "#f43f79",
	},
	{
		id: 8,
		title: "Low Earth Parade",
		jp: "低軌道行進",
		type: "TV" as const,
		ep: 12,
		aired: "Winter 2026",
		studio: "Azure Lab",
		genres: ["Sci-Fi", "Drama"],
		score: 7.62,
		members: 72_100,
		status: "Completed" as const,
		glyph: "軌",
		progress: 12,
		color: "#34d3b7",
	},
];

export type AnimeEntry = (typeof ANIME_LIBRARY)[number];

export const WATCHLIST = ANIME_LIBRARY.filter((a) => a.status !== "Plan to Watch");

export const CONVERSATIONS = [
	{ id: "c1", title: "Hollow Orchestra conductor theory", when: "2m ago", active: true },
	{ id: "c2", title: "Top 10 slow-burn Spring 2026 picks", when: "1h ago", active: false },
	{
		id: "c3",
		title: "Compare Silent Lantern vs Paperbound pacing",
		when: "Yesterday",
		active: false,
	},
	{ id: "c4", title: "Why did Dust & Iron drop in score?", when: "Yesterday", active: false },
	{ id: "c5", title: "Studio Maple director lineage", when: "3d ago", active: false },
	{ id: "c6", title: "Reddit sentiment for ep 9 of Paperbound", when: "4d ago", active: false },
];

export const SEASONAL_SENT = [
	{ d: "Apr 08", v: 62 },
	{ d: "Apr 09", v: 65 },
	{ d: "Apr 10", v: 61 },
	{ d: "Apr 11", v: 68 },
	{ d: "Apr 12", v: 74 },
	{ d: "Apr 13", v: 72 },
	{ d: "Apr 14", v: 78 },
	{ d: "Apr 15", v: 80 },
	{ d: "Apr 16", v: 83 },
	{ d: "Apr 17", v: 77 },
	{ d: "Apr 18", v: 82 },
	{ d: "Apr 19", v: 86 },
	{ d: "Apr 20", v: 79 },
	{ d: "Apr 21", v: 84 },
	{ d: "Apr 22", v: 88 },
	{ d: "Apr 23", v: 91 },
];

export const SILENT_LANTERN_SENT = [
	{ d: "Ep 1", v: 78 },
	{ d: "Ep 2", v: 75 },
	{ d: "Ep 3", v: 81 },
	{ d: "Ep 4", v: 79 },
	{ d: "Ep 5", v: 86 },
	{ d: "Ep 6", v: 88 },
	{ d: "Ep 7", v: 91 },
];

export type DataPoint = { d: string; v: number };

export const NAV_ITEMS = [
	{ key: "home", label: "Home", icon: "home" as const, group: "main" as const },
	{ key: "catalog", label: "Catalog Explorer", icon: "catalog" as const, group: "main" as const },
	{
		key: "watchlist",
		label: "Watchlist",
		icon: "watch" as const,
		group: "main" as const,
		count: 7,
	},
	{ key: "readlist", label: "Readlist", icon: "book" as const, group: "main" as const, count: 12 },
	{ key: "chat", label: "Chat", icon: "chat" as const, group: "research" as const, pill: "Live" },
	{ key: "theories", label: "Theories", icon: "theory" as const, group: "research" as const },
	{ key: "graph", label: "Graph Explorer", icon: "graph" as const, group: "research" as const },
	{ key: "reports", label: "Reports", icon: "report" as const, group: "delivery" as const },
	{
		key: "analytics",
		label: "Analytics",
		icon: "chart" as const,
		group: "delivery" as const,
		role: "admin",
	},
	{ key: "settings", label: "Settings", icon: "settings" as const, group: "system" as const },
] as const;

export type NavItem = (typeof NAV_ITEMS)[number];

export const NAV_GROUPS: Record<string, string> = {
	main: "Library",
	research: "Research",
	delivery: "Delivery",
	system: "System",
};
